Ext.define("cfa.view.DateUnit",{

	extend: "Ext.Container",
	requires: ["Ext.TabPanel","Ext.Panel",],
	
	xtype: "dateunit",
	config:{
		xtype:'panel',
				name:'monthBox',
				id:'monthBox',
				width:'100%',
				height:206,
				scrollable:'horizontal',
				cls:'monthbox',
				items:[{
					xtype:'panel',
					width:'100%',
					minWidth:260,
					layout: "hbox",
					cls:'weekBox',
					id:'firstWeek',
					defaults:{
						xtype:'panel',
						width:'14%',
						height:40,
						cls:'datebox',
					},
					items:[{
						id:"firstDay",
						items:[{
							xtype:'button',
							text:'1',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_0",
						}]
					},{
						items:[{
							xtype:'button',
							text:'2',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_1",
						}]
					},{
						items:[{
							xtype:'button',
							text:'3',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_2",
						}]
					},{
						items:[{
							xtype:'button',
							text:'4',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_3",
						}]
					},{
						items:[{
							xtype:'button',
							text:'5',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_4",
						}]
					},{
						items:[{
							xtype:'button',
							text:'6',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_5",
						}]
					},{
						items:[{
							xtype:'button',
							text:'7',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_6",
						}]
					}],
				},{
					xtype:'panel',
					width:'100%',
					minWidth:260,
					layout: "hbox",
					cls:'weekBox',
					defaults:{
						xtype:'panel',
						width:'14%',
						height:40,
						cls:'datebox',
					},
					items:[{
						items:[{
							xtype:'button',
							text:'8',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_7",
						}]
					},{
						items:[{
							xtype:'button',
							text:'9',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_8",
						}]
					},{
						items:[{
							xtype:'button',
							text:'10',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_9",
						}]
					},{
						items:[{
							xtype:'button',
							text:'11',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_10",
						}]
					},{
						items:[{
							xtype:'button',
							text:'12',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_11",
						}]
					},{
						items:[{
							xtype:'button',
							text:'13',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_12",
						}]
					},{
						items:[{
							xtype:'button',
							text:'14',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_13",
						}]
					}],
				},{
					xtype:'panel',
					width:'100%',
					minWidth:260,
					layout: "hbox",
					cls:'weekBox',
					defaults:{
						xtype:'panel',
						width:'14%',
						height:40,
						cls:'datebox',
					},
					items:[{
						items:[{
							xtype:'button',
							text:'15',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_14",
						}]
					},{
						items:[{
							xtype:'button',
							text:'16',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_15",
						}]
					},{
						items:[{
							xtype:'button',
							text:'17',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_16",
						}]
					},{
						items:[{
							xtype:'button',
							text:'18',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_17",
						}]
					},{
						items:[{
							xtype:'button',
							text:'19',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_18",
						}]
					},{
						items:[{
							xtype:'button',
							text:'20',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_19",
						}]
					},{
						items:[{
							xtype:'button',
							text:'21',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_20",
						}]
					}],
				},{
					xtype:'panel',
					width:'100%',
					minWidth:260,
					layout: "hbox",
					cls:'weekBox',
					defaults:{
						xtype:'panel',
						width:'14%',
						height:40,
						cls:'datebox',
					},
					items:[{
						items:[{
							xtype:'button',
							text:'22',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_21",
						}]
					},{
						items:[{
							xtype:'button',
							text:'23',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_22",
						}]
					},{
						items:[{
							xtype:'button',
							text:'24',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_23",
						}]
					},{
						items:[{
							xtype:'button',
							text:'25',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_24",
						}]
					},{
						items:[{
							xtype:'button',
							text:'26',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_25",
						}]
					},{
						items:[{
							xtype:'button',
							text:'27',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_26",
						}]
					},{
						items:[{
							xtype:'button',
							text:'28',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_27",
						}]
					}],
				},{
					xtype:'panel',
					width:'100%',
					minWidth:260,
					layout: "hbox",
					cls:'weekBox',
					defaults:{
						xtype:'panel',
						width:'14%',
						height:40,
						cls:'datebox',
					},
					items:[{
						items:[{
							xtype:'button',
							text:'29',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_28",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_29",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_30",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_31",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_32",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_33",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_34",
						}]
					}],
				},{
					xtype:'panel',
					width:'100%',
					minWidth:260,
					layout: "hbox",
					cls:'weekBox',
					defaults:{
						xtype:'panel',
						width:'14%',
						height:40,
						cls:'datebox',
					},
					items:[{
						items:[{
							xtype:'button',
							// text:'',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_35",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_36",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_37",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_38",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_39",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_40",
						}]
					},{
						items:[{
							xtype:'button',
							ui:'plain',
							width:40,
							height:40,
							cls:'dateBtn',
							id:"dayBtn_41",
						}]
					}],
				}],


	},//结束config

	//初始化当前月份
	initMonth:function(){
		var today = new Date();
		this.setMonth(today.getFullYear(),today.getMonth()+1);
		var todayBtn = Ext.getCmp("dayBtn_" + (today.getDate()-1));
		todayBtn.setCls("activeDayBtn");
	},

	//把日历控件设置为具体某个月的时间
	setMonth:function(Year,Month){
		var firstDay = new Date(Year,Month-1,1)
		var day = firstDay.getDay();
		var dayCount = this.DayNumOfMonth(Year,Month);
		if(day+dayCount >35){
			this.setHeight(240);
		}
		for(var i = 0; i < day; i++){
			var dayBtn = Ext.getCmp("dayBtn_" + i);
			dayBtn.setText("");
		};
		for(var i = 0 ; i < dayCount; i++){
			var dayBtn = Ext.getCmp("dayBtn_" + (day+i));
			dayBtn.setText(i+1);
		};
		for(var i = dayCount+day; i < 35; i++){
				var dayBtn = Ext.getCmp("dayBtn_" + i);
				dayBtn.setText("");
		}
	},

	//获取具体年月的总天数，格式：eg：2015,3
	DayNumOfMonth:function(Year,Month)
	{
		Month--;
		var d = new Date(Year,Month,1);
		d.setDate(d.getDate()+32-d.getDate());
		return (32-d.getDate());
	},
});