Ext.define("cfa.view.me.MuteTimeView",{

	extend: "Ext.Container",
	requires: ["Ext.TabPanel","Ext.Panel","Ext.field.Toggle","Ext.picker.Picker"],
	
	xtype: "mutetimeview",
	timeselection:'start',
	config:{
			/*静音设置页面*/
			layout: "vbox",
			width: "100%",
			height:'100%',
			fullscreen: true,
			// showAnimation:'pop',
			hideAnimation:'popOut',
			// scrollable:'vertical',
			default:{
				styleHtmlContent:true,
			},
			items: [
			{	
				xtype:'panel',
				layout: "vbox",
				width: "100%",
				height:'100%',
				fullscreen: true,
				// showAnimation:'pop',
				hideAnimation:'popOut',
				// scrollable:'vertical',
				default:{
					styleHtmlContent:true,
				},
				items:[{
					xtype: "toolbar",
					title: "静音设置", 
					docked: "top",
					zIndex:2,
					items:[{
						html:'返回',
						name:'backbtn_mute',
						ui:'plain',
					}],
				},{
					xtype:'tipspanel',
					id:'tipsBox_mutetime',
				},{//开始时间段
					xtype:'button',
					name:'startTimeBtn',
					cls:'psnMenu',
					ui: 'plain',
					html:['<div class="psnInfItem"><div class="psnInfItemTitle">开始</div><div id="startTime" class="psnInfcontent">23:00</div></div>']
				},{//结束时间段
					xtype:'button',
					name:'endTimeBtn',
					cls:'psnMenu psninfMenu',
					ui: 'plain',
					html:['<div class="psnInfItem"><div class="psnInfItemTitle">结束</div><div id="endTime" class="psnInfcontent">8:30</div></div>']
				}]
				
			},{
				xtype:'panel',
				name:'pickerBox',
				id:'pickerBox',
				cls:'pickerBox',
				modal:true,
				zIndex:99,
				centered:true,
				hidden:true,
				layout:'vbox',
				hideOnMaskTap:true,
				height:270,
				width:'80%',
				items:[
				{
					xtype:'picker',
					useTitles:true,
					id:'timePicker',
					modal:false,
					cancelButton:false,
					doneButton:false,
					width:'100%',
					cls:'picker',
					slots:[{
						name:'hour',
						title:'时',
						data:[
							{text:'0',value:0},
							{text:'1',value:1},
							{text:'2',value:2},
							{text:'3',value:3},
							{text:'4',value:4},
							{text:'5',value:5},
							{text:'6',value:6},
							{text:'7',value:7},
							{text:'8',value:8},
							{text:'9',value:9},
							{text:'10',value:10},
							{text:'11',value:11},
							{text:'12',value:12},
							{text:'13',value:13},
							{text:'14',value:14},
							{text:'15',value:15},
							{text:'16',value:16},
							{text:'17',value:17},
							{text:'18',value:18},
							{text:'19',value:19},
							{text:'20',value:20},
							{text:'21',value:21},
							{text:'22',value:22},
							{text:'23',value:23},
						]
					},
					{
						name:'minute',
						title:'分',
						data:[
							{text:'00',value:0},
							{text:'01',value:1},
							{text:'02',value:2},
							{text:'03',value:3},
							{text:'04',value:4},
							{text:'05',value:5},
							{text:'06',value:6},
							{text:'07',value:7},
							{text:'08',value:8},
							{text:'09',value:9},
							{text:'10',value:10},
							{text:'11',value:11},
							{text:'12',value:12},
							{text:'13',value:13},
							{text:'14',value:14},
							{text:'15',value:15},
							{text:'16',value:16},
							{text:'17',value:17},
							{text:'18',value:18},
							{text:'19',value:19},
							{text:'20',value:20},
							{text:'21',value:21},
							{text:'22',value:22},
							{text:'23',value:23},
							{text:'24',value:24},
							{text:'25',value:25},
							{text:'26',value:26},
							{text:'27',value:27},
							{text:'28',value:28},
							{text:'29',value:29},
							{text:'30',value:30},
							{text:'31',value:31},
							{text:'32',value:32},
							{text:'33',value:33},
							{text:'34',value:34},
							{text:'35',value:35},
							{text:'36',value:36},
							{text:'37',value:37},
							{text:'38',value:38},
							{text:'39',value:39},
							{text:'40',value:40},
							{text:'41',value:41},
							{text:'42',value:42},
							{text:'43',value:43},
							{text:'44',value:19},
							{text:'45',value:45},
							{text:'46',value:46},
							{text:'47',value:47},
							{text:'48',value:48},
							{text:'49',value:49},
							{text:'50',value:50},
							{text:'51',value:51},
							{text:'52',value:52},
							{text:'53',value:53},
							{text:'54',value:54},
							{text:'55',value:55},
							{text:'56',value:56},
							{text:'57',value:57},
							{text:'58',value:58},
							{text:'59',value:59},
						]
					}]
				},{//装载确定取消按钮的panel
					xtype:'panel',
					layout:'hbox',
					cls:'pickerBtnBox',
					width:'100%',
					items:[{
						xtype:'button',
						name:'cancelBtn',
						cls:'pickerBtn btn-border-right',
						text:'取消',
						width:'50%',
						ui:'plain',
					},{
						xtype:'button',
						name:'doneBtn',
						cls:'pickerBtn',
						text:'确定',
						width:'50%',
						ui:'plain',
					}]
				}],
			}],
	},

});